version: '3'
services: 
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        expose:
            - "3306"
        networks: 
            - docker_mevn
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: mondok
          MYSQL_USER: root
          MYSQL_PASSWORD: password

        volumes:
        - my-datavolume
    app:
      image: tobil/mondok:v1.0.0
      networks:
          - docker_mevn
      ports:
          - "3000:3000"
      expose:
          - "3000"
      environment:
          DB_HOST: db
          DB_USER: root
          DB_PASS: password
          DB_PORT: "3306"
          DB_NAME: mondok
networks:
    docker_mevn:
        driver: bridge
volumes:
  my-datavolume: